/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.ChiTietHoaDonBLL;
import BLL.ComboboxBLL;
import BLL.HoaDonBLL;
import BLL.LoaiBLL;
import BLL.LoginBLL;
import BLL.ThucDonBLL;
import DAL.BanDAL;
import DTO.ChiTietHoaDon;
import DTO.HoaDon;
import DTO.ThucDon;
import static Presentation.frmHome.soHoaDon;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LTSNLH5586
 */
public class jdSuaMon extends javax.swing.JDialog {

    /**
     * Creates new form JdOrder
     */
    public jdSuaMon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTenBan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtDVT = new javax.swing.JLabel();
        txtMinus = new javax.swing.JLabel();
        txtPlus = new javax.swing.JLabel();
        lblTenMon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 233, 193));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sửa Món :");

        lblTenBan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTenBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenBan.setText("Tên bàn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên Món: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Số Lượng: ");

        txtSoLuong.setText("1");
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyTyped(evt);
            }
        });

        txtDVT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDVT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDVT.setText("DVT");

        txtMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minus_25px.png"))); // NOI18N
        txtMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMinusMousePressed(evt);
            }
        });

        txtPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus Math_25px.png"))); // NOI18N
        txtPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlusMousePressed(evt);
            }
        });

        lblTenMon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenMon.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblTenBan, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(11, 58, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinus)
                        .addGap(11, 11, 11)
                        .addComponent(txtPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(lblTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenBan)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtMinus))
                    .addComponent(txtPlus)
                    .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 360, 210));

        jPanel3.setBackground(new java.awt.Color(255, 240, 213));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cocktail_48px_2.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 42, 45));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Orange Juice_48px.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 42, 45));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cherry_48px_1.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 42, 45));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 210));

        jPanel4.setBackground(new java.awt.Color(170, 155, 128));

        btnXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Checkmark_40px.png"))); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXacNhanMousePressed(evt);
            }
        });
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel_40px.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHuyMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnXacNhan)
                .addGap(69, 69, 69)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSoLuongKeyTyped

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnXacNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseEntered
        btnXacNhan.setBackground(new Color(180, 218, 255));
    }//GEN-LAST:event_btnXacNhanMouseEntered

    private void btnXacNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseExited
        btnXacNhan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnXacNhanMouseExited

    private void btnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseEntered
        btnHuy.setBackground(new Color(255, 170, 170));
    }//GEN-LAST:event_btnHuyMouseEntered

    private void btnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseExited
        btnHuy.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnHuyMouseExited

    private void btnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMousePressed
       // frmHome.selectBan = 0;
       // frmHome.trangThaiBan = 0;
       // frmHome.tenBan = "";
       // frmHome.soHoaDon = "";
        this.dispose();
        //System.out.println(frmHome.selectBan + frmHome.trangThaiBan);
    }//GEN-LAST:event_btnHuyMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ResultSet rsGetAllThucDon = ThucDonBLL.getAllThucDon();
        // ThucDonBLL.doDuLieuVaoBang(rsGetAllThucDon, tblthucDon);
        ResultSet rsGetAllLoai = LoaiBLL.getAllLoai();
        ThucDon thucDon =  ThucDonBLL.getThucDonById(frmHome.idThucDon);
       
        lblTenBan.setText(frmHome.tenBan);
        lblTenMon.setText(thucDon.getTenMon());
        txtSoLuong.setText(""+frmHome.soLuong+"");
        getDVT();
    }//GEN-LAST:event_formWindowOpened
    public void getDVT() {
        int idthucDon = frmHome.idThucDon;
        txtDVT.setText(ThucDonBLL.getThucDonById(idthucDon).getDonViTinh());
    }
    private void txtPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlusMousePressed
        int plus = Integer.parseInt(txtSoLuong.getText()) + 1;
        txtSoLuong.setText("" + plus + "");
    }//GEN-LAST:event_txtPlusMousePressed

    private void txtMinusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinusMousePressed
        int minus = Integer.parseInt(txtSoLuong.getText()) - 1;
        if (Integer.parseInt(txtSoLuong.getText()) > 1) {
            txtSoLuong.setText("" + minus + "");
        } else {
            txtSoLuong.setText("1");
        }

    }//GEN-LAST:event_txtMinusMousePressed

    private void btnXacNhanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMousePressed
        int idthucDon = frmHome.idThucDon;

        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String donGia = ThucDonBLL.getThucDonById(idthucDon).getDonGia().toString();
        int gia = Integer.parseInt(donGia) * soLuong;

      //  DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
     //   DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
     //   LocalDateTime now = LocalDateTime.now();
     //   String gioDen = dtf.format(now);
    //    String createSoHoaDon = dtf1.format(now);
       

       // ChiTietHoaDonBLL.getChiTietHoaDonBySoHoaDonVaIdThucDon(frmHome.soHoaDon, idthucDon);
       // boolean updateSoLuongMon = ChiTietHoaDonBLL.updateSoLuongMon;

     //   if (updateSoLuongMon) {
          //  int newsoLuong = soLuong + ChiTietHoaDonBLL.getSoLuong;
           // int newgia = Integer.parseInt(donGia) * newsoLuong;
            ChiTietHoaDonBLL.updateSoLuongMonChitietHoaDon(soLuong, frmHome.idChiTietHoaDon, new BigDecimal(gia));
           // ChiTietHoaDonBLL.getSoLuong = 0;
           // ChiTietHoaDonBLL.idChiTietHoaDon = 0;
          //  ChiTietHoaDonBLL.updateSoLuongMon = false;
      //  } else {
            // Add Chi Tiết Hóa ĐƠn
         //   ChiTietHoaDon cthd = new ChiTietHoaDon(frmHome.soHoaDon, idthucDon, soLuong, new BigDecimal(gia));
          //  ChiTietHoaDonBLL.addChiTietHoaDon(cthd);
      //  }

        // Update Tổng Tiền Chi Tiết Hóa Đon
        ChiTietHoaDonBLL.getChiTietHoaDonBySoHoaDonStr(frmHome.soHoaDon);
        int tongTien = ChiTietHoaDonBLL.tongTien;
        HoaDonBLL.updateTongTienHoaDon(frmHome.soHoaDon, new BigDecimal(tongTien));

        JOptionPane.showMessageDialog(null, "Edit Món Thành Công !");

        ChiTietHoaDonBLL.tongTien = 0;
    }//GEN-LAST:event_btnXacNhanMousePressed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
       
        if (Integer.parseInt(txtSoLuong.getText()) ==  0 ||Integer.parseInt(txtSoLuong.getText()) < 1) {
            txtSoLuong.setText("1");
        }
    }//GEN-LAST:event_txtSoLuongKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdSuaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdSuaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdSuaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdSuaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdSuaMon dialog = new jdSuaMon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblTenBan;
    private javax.swing.JLabel lblTenMon;
    private javax.swing.JLabel txtDVT;
    private javax.swing.JLabel txtMinus;
    private javax.swing.JLabel txtPlus;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
