/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.ChiTietHoaDonBLL;
import BLL.HoaDonBLL;
import BLL.ThucDonBLL;
import DAL.BanDAL;
import DTO.HoaDon;
import DTO.ThucDon;
import static Presentation.frmHome.idChiTietHoaDon;
import static Presentation.frmHome.idThucDon;
import static Presentation.frmHome.soHoaDon;
import static Presentation.frmHome.soLuong;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author LTSNLH5586
 */
public class jdThanhToan extends javax.swing.JDialog {

    /**
     * Creates new form jdThanhToan
     */
    public jdThanhToan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGoiMon = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        lblTongTien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTongCong = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhuThu = new javax.swing.JTextField();
        txtThueVAT = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        lblThongTinBan = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblTienTraKhach = new javax.swing.JLabel();

        jPopupMenu1.setBackground(new java.awt.Color(238, 253, 221));

        jMenuItem1.setBackground(new java.awt.Color(251, 198, 174));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_25px.png"))); // NOI18N
        jMenuItem1.setText("Edit");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);
        jPopupMenu1.add(jSeparator5);

        jMenuItem2.setBackground(new java.awt.Color(249, 178, 179));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete Property_25px.png"))); // NOI18N
        jMenuItem2.setText("Delete");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 239, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(168, 154, 113));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 50, 71));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cash in Hand_40px_1.png"))); // NOI18N
        jLabel1.setText("THANH TOÁN HÓA ĐƠN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 1, 820, 70));

        jPanel4.setBackground(new java.awt.Color(253, 239, 198));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Bàn"));

        tblGoiMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "SoHoaDon", "Tên Món", "Số Lượng", "Giá", "Tổng Giá"
            }
        ));
        tblGoiMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGoiMonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblGoiMonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblGoiMonMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblGoiMon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 490, 210));

        jPanel5.setBackground(new java.awt.Color(175, 223, 241));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Thanh Toán"));

        jLabel2.setText("Tổng Tiền:");

        txtGiamGia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGiamGia.setText("0");
        txtGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGiamGiaMouseClicked(evt);
            }
        });
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyTyped(evt);
            }
        });

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("100");

        jLabel6.setText("Giảm Giá (%) :");

        jLabel5.setText("Phụ Thu (VND) :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tổng Cộng : ");

        lblTongCong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTongCong.setForeground(new java.awt.Color(255, 51, 51));
        lblTongCong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongCong.setText("200");

        jLabel10.setText("Thuế VAT (%) :");

        txtPhuThu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPhuThu.setText("0");
        txtPhuThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhuThuMouseClicked(evt);
            }
        });
        txtPhuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhuThuActionPerformed(evt);
            }
        });
        txtPhuThu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhuThuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhuThuKeyTyped(evt);
            }
        });

        txtThueVAT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtThueVAT.setText("0");
        txtThueVAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThueVATMouseClicked(evt);
            }
        });
        txtThueVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThueVATActionPerformed(evt);
            }
        });
        txtThueVAT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThueVATKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtThueVATKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(lblTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThueVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTongTien))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10))
                    .addComponent(txtThueVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(lblTongCong)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 270, 300));

        jPanel7.setBackground(new java.awt.Color(169, 255, 176));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao Tác"));

        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Checkmark_25px.png"))); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXacNhanMousePressed(evt);
            }
        });
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Unavailable_25px.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete_25px_2.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHuyMousePressed(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print_25px.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnHuy)
                .addGap(16, 16, 16)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnIn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuy)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel)
                        .addComponent(btnXacNhan)))
                .addGap(3, 3, 3))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 490, 80));

        jPanel6.setBackground(new java.awt.Color(253, 239, 198));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Bàn"));

        lblThongTinBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTinBan.setText("jLabel3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongTinBan, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongTinBan)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 270, 60));

        jPanel8.setBackground(new java.awt.Color(246, 217, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tính Tiền"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tiền Khách Đưa : ");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 16, -1, 32));

        txtTienKhachDua.setText("0");
        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyTyped(evt);
            }
        });
        jPanel8.add(txtTienKhachDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 16, 77, 32));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 16, 10, 32));

        lblTienTraKhach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTienTraKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTienTraKhach.setText("Tiền Trả Khách : 20");
        jPanel8.add(lblTienTraKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 16, 177, 32));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 490, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyReleased

        if (txtGiamGia.getText().equals("")) {
            txtGiamGia.setText("0");
        } else if (Integer.parseInt(txtGiamGia.getText()) > 100) {
            txtGiamGia.setText("100");
        }

        tongCong();
    }//GEN-LAST:event_txtGiamGiaKeyReleased

    private void txtGiamGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtGiamGiaKeyTyped

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
       
        tienThoiKhach();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void txtTienKhachDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachDuaKeyTyped

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblGoiMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGoiMonMousePressed

    }//GEN-LAST:event_tblGoiMonMousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        frmHome frmHome = new frmHome();
        jdSuaMon jd = new jdSuaMon(frmHome, true);
        jd.setVisible(true);
        updateTongTien();
        loadDuLieuVaoTabelGoiMon();
        tongCong();
       
       // setTongTien();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        ThucDon thucDon = ThucDonBLL.getThucDonById(frmHome.idThucDon);

        int kq = JOptionPane.showConfirmDialog(null, "Bạn Muốn Hủy Món :" + thucDon.getTenMon() + " - " + frmHome.tenBan + " ?", "Phần Mềm Quản Lý Quán Cafe", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            ChiTietHoaDonBLL.deleteChiTietHoaDon(idChiTietHoaDon);

            ChiTietHoaDonBLL.getChiTietHoaDonBySoHoaDonStr(soHoaDon);
            int tongTien = ChiTietHoaDonBLL.tongTien;
            HoaDonBLL.updateTongTienHoaDon(soHoaDon, new BigDecimal(tongTien));

        }
        updateTongTien();
        loadDuLieuVaoTabelGoiMon();
        tongCong();
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadDuLieuVaoTabelGoiMon();
        thongTinBan();
        updateTongTien();
       tongCong();
        lblTienTraKhach.setText("Tiền Trả Khách : ");
      //  setTongTien();
    }//GEN-LAST:event_formWindowOpened

    private void tblGoiMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGoiMonMouseClicked
        int index = tblGoiMon.getSelectedRow();
        idChiTietHoaDon = Integer.parseInt(tblGoiMon.getValueAt(index, 0).toString());
        idThucDon = Integer.parseInt(tblGoiMon.getValueAt(index, 6).toString());
        soLuong = Integer.parseInt(tblGoiMon.getValueAt(index, 3).toString());
    }//GEN-LAST:event_tblGoiMonMouseClicked

    private void tblGoiMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGoiMonMouseReleased
        int r = tblGoiMon.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tblGoiMon.getRowCount()) {
            tblGoiMon.setRowSelectionInterval(r, r);
        } else {
            tblGoiMon.clearSelection();
        }

        int rowindex = tblGoiMon.getSelectedRow();
        if (rowindex < 0) {
            return;
        }
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable) {
            int index = tblGoiMon.getSelectedRow();
            idChiTietHoaDon = Integer.parseInt(tblGoiMon.getValueAt(index, 0).toString());
            idThucDon = Integer.parseInt(tblGoiMon.getValueAt(index, 6).toString());
            soLuong = Integer.parseInt(tblGoiMon.getValueAt(index, 3).toString());
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblGoiMonMouseReleased

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        this.dispose();
    }//GEN-LAST:event_btnCancelMousePressed

    private void txtPhuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhuThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhuThuActionPerformed

    private void txtPhuThuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhuThuKeyReleased
        tongCong();
    }//GEN-LAST:event_txtPhuThuKeyReleased

    private void txtPhuThuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhuThuKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPhuThuKeyTyped

    private void txtThueVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThueVATActionPerformed

    }//GEN-LAST:event_txtThueVATActionPerformed

    private void txtThueVATKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThueVATKeyReleased

        tongCong();
    }//GEN-LAST:event_txtThueVATKeyReleased

    private void txtThueVATKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThueVATKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtThueVATKeyTyped

    private void txtGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGiamGiaMouseClicked
      
        if (txtGiamGia.getText().equals("0")) {
            txtGiamGia.setText("");
        }
        if (txtPhuThu.getText().equals("")) {
            txtPhuThu.setText("0");
        }
         if (txtThueVAT.getText().equals("")) {
            txtThueVAT.setText("0");
        }
    }//GEN-LAST:event_txtGiamGiaMouseClicked

    private void txtThueVATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThueVATMouseClicked
        if (txtThueVAT.getText().equals("0")) {
            txtThueVAT.setText("");
        }
        if (txtPhuThu.getText().equals("")) {
            txtPhuThu.setText("0");
        }
         if (txtGiamGia.getText().equals("")) {
            txtGiamGia.setText("0");
        }
    }//GEN-LAST:event_txtThueVATMouseClicked

    private void txtPhuThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhuThuMouseClicked
        if (txtPhuThu.getText().equals("0")) {
            txtPhuThu.setText("");
        }
        if (txtThueVAT.getText().equals("")) {
            txtThueVAT.setText("0");
        }
         if (txtGiamGia.getText().equals("")) {
            txtGiamGia.setText("0");
        }
    }//GEN-LAST:event_txtPhuThuMouseClicked

    private void btnXacNhanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMousePressed
       int kq = JOptionPane.showConfirmDialog(null, "Bạn Muốn Thanh Toán : " + frmHome.tenBan + " ?", "Phần Mềm Quản Lý Quán Cafe", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            HoaDonBLL.updateTrangThaiHoaDon(soHoaDon, 1);
            BanDAL.updateTrangThaiVaSoHoaDon(frmHome.selectBan, null, 1);
            this.dispose();

        }
        
       
    }//GEN-LAST:event_btnXacNhanMousePressed

    private void btnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMousePressed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn Muốn Hủy Hóa Đơn: " + frmHome.soHoaDon + " " +frmHome.tenBan +" ?", "Phần Mềm Quản Lý Quán Cafe", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            HoaDonBLL.updateTrangThaiHoaDon(soHoaDon, 2);
            BanDAL.updateTrangThaiVaSoHoaDon(frmHome.selectBan, null, 1);
            this.dispose();

        }
    }//GEN-LAST:event_btnHuyMousePressed
    public void loadDuLieuVaoTabelGoiMon() {
        ResultSet rsGetChiTietThucDonBySoHoaDon = ChiTietHoaDonBLL.getChiTietThucDonBySoHoaDon(soHoaDon);
        ChiTietHoaDonBLL.DoDuLieuVaoJTableChiTietHoaDon(rsGetChiTietThucDonBySoHoaDon, tblGoiMon);
    }

    public void updateTongTien() {
        HoaDon hoaDon = HoaDonBLL.getHoaDonBySoHoaDon(soHoaDon);
        lblTongTien.setText(hoaDon.getTongtien().toString());
        ChiTietHoaDonBLL.tongTien = 0;
    }
 public void thongTinBan() {
        HoaDon hoaDon = HoaDonBLL.getHoaDonBySoHoaDon(soHoaDon);
        lblThongTinBan.setText(frmHome.tenBan + " - "+ hoaDon.getGioden());
        
    }
    private void setTongCong() {
        HoaDon hoaDon = HoaDonBLL.getHoaDonBySoHoaDon(soHoaDon);
        lblTongCong.setText(hoaDon.getTongtien().toString());
    }
    
    private void tongCong() {
        int tongTien = Integer.parseInt(lblTongTien.getText());
        int giamGia = Integer.parseInt(txtGiamGia.getText());
        int thueVAT = Integer.parseInt(txtThueVAT.getText());
        int phuThu = Integer.parseInt(txtPhuThu.getText());

        int tongCong = (tongTien + (tongTien * thueVAT / 100) + phuThu) - (tongTien * giamGia / 100);
        
        lblTongCong.setText("" + tongCong + "");
    }
    private void tienThoiKhach(){
        int tienKhachDua =Integer.parseInt(txtTienKhachDua.getText());
        int tongTien = Integer.parseInt(lblTongTien.getText());
        int tienThoiKhach = tienKhachDua - tongTien;
        lblTienTraKhach.setText("Tiền Trả Khách : " + tienThoiKhach);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdThanhToan dialog = new jdThanhToan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblThongTinBan;
    private javax.swing.JLabel lblTienTraKhach;
    private javax.swing.JLabel lblTongCong;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblGoiMon;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtPhuThu;
    private javax.swing.JTextField txtThueVAT;
    private javax.swing.JTextField txtTienKhachDua;
    // End of variables declaration//GEN-END:variables
}
